-- seed_definitions_fixed.sql
-- Run each section separately in Supabase SQL Editor

-- ============================================
-- ALIGNMENT DEFS
-- ============================================
INSERT INTO alignment_defs (id, name, description, passive_bonuses, unique_mechanic, starting_bias) VALUES
('germany', 'Germany', 'Blitzkrieg doctrine. Fast armor, combined arms bonus.', '{"armor_speed":1.2,"attack_vs_stationary":1.15,"encirclement_bonus":1.1}', '{"name":"Combined Arms","description":"Adjacent different unit categories get +15% attack","bonus":0.15}', '{"resources_multiplier":0.8,"starting_units":{"riflemen":10,"light_tank":2,"field_gun":2},"extra_tiles":1}'),
('uk', 'United Kingdom', 'Naval supremacy and colonial supply lines. Strong intelligence network.', '{"naval_combat":1.2,"trade_income":1.15,"code_breaking_speed":1.25}', '{"name":"Naval Supremacy","description":"Naval units get +20% in home waters, trade routes +15% income","naval_bonus":0.20,"trade_bonus":0.15}', '{"resources_multiplier":0.9,"starting_units":{"riflemen":8,"engineers":2,"field_gun":1},"extra_tiles":0,"bonus_trade_routes":2}'),
('usa', 'United States of America', 'Industrial powerhouse. Unmatched production capacity once mobilized.', '{"production_speed":1.2,"resource_extraction":1.1,"unit_cost_reduction":0.9}', '{"name":"Arsenal of Democracy","description":"Factories produce 20% faster, lend-lease at reduced cost","production_bonus":0.20,"lend_lease_efficiency":0.8}', '{"resources_multiplier":1.3,"starting_units":{"riflemen":6,"armored_car":1},"extra_tiles":0}'),
('ussr', 'Soviet Union', 'Vast manpower reserves. Defense in depth, scorched earth capability.', '{"manpower_generation":1.3,"defense_on_own_territory":1.2,"winter_combat":1.25}', '{"name":"Deep Battle","description":"Units on owned territory get +20% defense. Scorched earth denies resources for 5 turns","defense_bonus":0.20,"scorched_earth_turns":5}', '{"resources_multiplier":1.0,"starting_units":{"riflemen":14,"field_gun":1},"extra_tiles":2,"manpower_bonus":50}'),
('japan', 'Empire of Japan', 'Fanatical morale and island-hopping expertise. Strong naval aviation.', '{"morale_resistance":1.3,"amphibious_attack":1.2,"aircraft_carrier_capacity":1.25}', '{"name":"Bushido","description":"Units fight at full strength until 25% HP. Last stand +30% attack below 25%","last_stand_threshold":0.25,"last_stand_bonus":0.30}', '{"resources_multiplier":0.7,"starting_units":{"riflemen":12,"engineers":1,"field_gun":1},"extra_tiles":0}'),
('italy', 'Kingdom of Italy', 'Mediterranean control. Strong fortification and defensive engineering.', '{"fortification_strength":1.2,"naval_mediterranean":1.15,"building_cost_reduction":0.85}', '{"name":"Mare Nostrum","description":"Buildings cost 15% less, fortifications 20% stronger, Mediterranean naval bonus","building_discount":0.15,"fort_bonus":0.20}', '{"resources_multiplier":0.85,"starting_units":{"riflemen":8,"field_gun":2},"extra_tiles":0,"coastal_tiles_bonus":2}'),
('france', 'France', 'Fortification expertise and colonial reach. Strong initial defenses.', '{"fortification_defense":1.25,"colonial_resources":1.2,"artillery_accuracy":1.15}', '{"name":"Maginot Doctrine","description":"Pre-built fortifications on border tiles. Artillery +15% accuracy","starting_forts":3,"artillery_bonus":0.15}', '{"resources_multiplier":0.9,"starting_units":{"riflemen":8,"field_gun":3,"engineers":1},"extra_tiles":0,"starting_fort_level":2}');
