-- seed_units_fixed.sql
INSERT INTO unit_defs (id, name, category, description, attack, defense, hp, speed, train_cost, train_time, upkeep, special_abilities, prerequisites) VALUES
('riflemen', 'Riflemen', 'infantry', 'Standard infantry. The backbone of any army.', 10, 12, 100, 2.0, '{"manpower":50,"money":20}', 120, '{"food":1,"money":0.5}', '{}', '{"barracks":1}'),
('mg_squad', 'Machine Gun Squad', 'infantry', 'Defensive specialists. Excellent at holding positions.', 8, 18, 100, 1.5, '{"manpower":60,"steel":10,"money":30}', 180, '{"food":1,"ammunition":1,"money":0.8}', '{"suppression":true,"defense_vs_infantry":1.3}', '{"barracks":1}'),
('mortar_team', 'Mortar Team', 'infantry', 'Indirect fire support against fortified positions.', 15, 6, 80, 1.5, '{"manpower":40,"steel":20,"ammunition":10,"money":25}', 180, '{"food":1,"ammunition":2,"money":0.6}', '{"indirect_fire":true,"range":2,"bonus_vs_fortified":1.3}', '{"barracks":1,"small_arms_improvement":1}'),
('engineers', 'Combat Engineers', 'infantry', 'Build/repair structures, clear mines, bridge rivers.', 6, 8, 90, 2.0, '{"manpower":60,"steel":30,"money":40}', 240, '{"food":1,"money":1.0}', '{"can_build":true,"can_repair":true,"can_clear_mines":true,"can_bridge":true}', '{"barracks":1}'),
('paratroopers', 'Paratroopers', 'infantry', 'Elite airborne troops dropped behind enemy lines.', 14, 10, 90, 2.0, '{"manpower":80,"money":60}', 360, '{"food":1,"money":1.2}', '{"can_airdrop":true,"surprise_attack_bonus":1.25}', '{"barracks":2,"advanced_tactics":1}'),
('light_tank', 'Light Tank', 'armor', 'Fast, lightly armored. Good for flanking and recon.', 20, 18, 150, 3.0, '{"steel":80,"rubber":20,"oil":10,"money":100}', 300, '{"oil":2,"money":1.0}', '{"flanking_bonus":1.2}', '{"tank_factory":1}'),
('medium_tank', 'Medium Tank', 'armor', 'Well-balanced tank with good firepower and armor.', 30, 28, 200, 2.5, '{"steel":150,"rubber":30,"oil":20,"money":180}', 480, '{"oil":3,"money":1.5}', '{"breakthrough_bonus":1.15}', '{"tank_factory":2,"armor_plating":1}'),
('heavy_tank', 'Heavy Tank', 'armor', 'Heavily armored behemoth. Devastating but slow.', 45, 40, 300, 1.5, '{"steel":300,"rubber":40,"oil":30,"money":350}', 720, '{"oil":5,"money":2.5}', '{"bonus_vs_fortifications":1.3,"intimidation":true}', '{"tank_factory":3,"heavy_armor":1}'),
('armored_car', 'Armored Car', 'armor', 'Fast recon vehicle with extended vision range.', 12, 10, 80, 4.0, '{"steel":40,"rubber":15,"oil":5,"money":50}', 180, '{"oil":1,"money":0.5}', '{"recon":true,"vision_bonus":2,"can_spot_mines":true}', '{"tank_factory":1}'),
('halftrack', 'Halftrack', 'armor', 'Armored personnel carrier for infantry.', 8, 12, 120, 3.0, '{"steel":60,"rubber":20,"money":70}', 240, '{"oil":1.5,"money":0.8}', '{"transport_capacity":2,"mounted_fire":true}', '{"tank_factory":1}'),
('field_gun', 'Field Gun', 'artillery', 'Standard artillery piece for fire support.', 25, 4, 60, 1.0, '{"steel":60,"money":50}', 240, '{"ammunition":2,"money":0.5}', '{"range":2,"setup_time":1}', '{"barracks":1}'),
('howitzer', 'Howitzer', 'artillery', 'Heavy artillery devastating against fortifications.', 40, 3, 50, 0.8, '{"steel":120,"money":100}', 360, '{"ammunition":4,"money":1.0}', '{"range":3,"bonus_vs_fortifications":1.5,"splash_damage":true}', '{"barracks":2,"small_arms_improvement":1}'),
('anti_tank_gun', 'Anti-Tank Gun', 'artillery', 'Specialized gun to destroy armored vehicles.', 35, 5, 50, 0.5, '{"steel":80,"tungsten":5,"money":70}', 300, '{"ammunition":2,"money":0.7}', '{"range":2,"bonus_vs_armor":1.5,"armor_piercing":true}', '{"barracks":2,"armor_plating":1}'),
('aa_gun', 'Anti-Aircraft Gun', 'artillery', 'Fires at enemy aircraft for air defense.', 5, 3, 50, 1.0, '{"steel":70,"money":60}', 240, '{"ammunition":2,"money":0.5}', '{"anti_air":true,"aa_attack":30,"aa_range":3}', '{"barracks":1}'),
('rocket_artillery', 'Rocket Artillery', 'artillery', 'Devastating area bombardment but inaccurate.', 50, 2, 40, 0.8, '{"steel":100,"ammunition":20,"money":120}', 420, '{"ammunition":5,"money":1.2}', '{"range":4,"area_damage":true,"accuracy":0.6,"morale_damage":1.5}', '{"barracks":2,"advanced_tactics":1}');
